[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "gunicorn --chdir backend \"app:create_app()\" --bind 0.0.0.0:$PORT"
