[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend"
]

[start]
cmd = "gunicorn --chdir backend \"app:create_app()\" --bind 0.0.0.0:$PORT"
