"""add handicap_index to matchupplayer

Revision ID: 104217612ca1
Revises: 767a82b2dc22
Create Date: 2026-04-24 14:37:05.327160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104217612ca1'
down_revision = '767a82b2dc22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handicap_index', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup_players', schema=None) as batch_op:
        batch_op.drop_column('handicap_index')

    # ### end Alembic commands ###
