"""add yardage to holes

Revision ID: 36a7f3c946c2
Revises: 56c7176a9457
Create Date: 2026-04-09 21:31:43.331936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a7f3c946c2'
down_revision = '56c7176a9457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yardage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holes', schema=None) as batch_op:
        batch_op.drop_column('yardage')

    # ### end Alembic commands ###
