"""add use_handicaps to matchups

Revision ID: 4506cf8c7fe2
Revises: 9e23d5117e58
Create Date: 2026-04-09 21:51:21.666683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4506cf8c7fe2'
down_revision = '9e23d5117e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_handicaps', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.drop_column('use_handicaps')

    # ### end Alembic commands ###
