"""add course logo

Revision ID: 474b92da496f
Revises: 104217612ca1
Create Date: 2026-05-09 14:21:03.650087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474b92da496f'
down_revision = '104217612ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
