"""Add custom team names

Revision ID: 56c7176a9457
Revises: f379dea5f81c
Create Date: 2026-04-09 21:13:10.687499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c7176a9457'
down_revision = 'f379dea5f81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_a_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('team_b_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_column('team_b_name')
        batch_op.drop_column('team_a_name')

    # ### end Alembic commands ###
