"""add_profile_picture_to_players

Revision ID: 767a82b2dc22
Revises: a10a4856bbfd
Create Date: 2026-04-12 13:13:13.251696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767a82b2dc22'
down_revision = 'a10a4856bbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
