"""add hole_start hole_end to matchups

Revision ID: 9e23d5117e58
Revises: 36a7f3c946c2
Create Date: 2026-04-09 21:40:29.836016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e23d5117e58'
down_revision = '36a7f3c946c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hole_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hole_end', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.drop_column('hole_end')
        batch_op.drop_column('hole_start')

    # ### end Alembic commands ###
