"""add_gender_and_female_ratings

Revision ID: a10a4856bbfd
Revises: efe6fa1d73e8
Create Date: 2026-04-11 20:22:06.162968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10a4856bbfd'
down_revision = 'efe6fa1d73e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.alter_column('scoring_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'match_play'"))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False, server_default='male'))

    with op.batch_alter_table('tees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_female', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('slope_female', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tees', schema=None) as batch_op:
        batch_op.drop_column('slope_female')
        batch_op.drop_column('rating_female')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.alter_column('scoring_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'match_play'"))

    # ### end Alembic commands ###
