"""add custom_pops to matchup_players

Revision ID: dfd6659fd737
Revises: 474b92da496f
Create Date: 2026-05-28 10:11:10.419681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd6659fd737'
down_revision = '474b92da496f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_pops', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup_players', schema=None) as batch_op:
        batch_op.drop_column('custom_pops')

    # ### end Alembic commands ###
