"""Add tee_time to matchups

Revision ID: efe6fa1d73e8
Revises: 4506cf8c7fe2
Create Date: 2026-04-09 22:18:38.841087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe6fa1d73e8'
down_revision = '4506cf8c7fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tee_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchups', schema=None) as batch_op:
        batch_op.drop_column('tee_time')

    # ### end Alembic commands ###
